### ISSUE TITLE
MaxIDE shows as "app description" in task manager

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#10]
Windows 10 lists MaxIDE as "app description" in the task manager.

**Comment by woollybah** [comment]
Cool. I never noticed :-)
Probably want to add an appropriate app settings file to the folder.

**Comment by woollybah** [comment]
I wonder if app description should default to the app name if nothing has been configured?

**Comment by GWRon** [comment]
Yes I think defaults should try to use se user data.

Username (home dir) could become "author" ...
Binary name could be app title.
Description could become "generic application created with BlitzMax (www.blitzmax.org)".

Only problem I see is "awareness". Some people do not know about these "app details" and might be surprised that their "useless-but-expensive.exe" (renamed to "wonderful-app.exe") exposes their opinion about something :-)

**Comment by woollybah** [comment]
Here's the defaults : https://github.com/bmx-ng/bmk/blob/master/bmk_config.bmx#L661

**Comment by GWRon** [comment]
Yes I was aware of that. But what I wanted to say is:

```BlitzMax
Function DefaultApplicationSettings:TMap()
	Local settings:TMap = New TMap
	settings.Insert("app.package", "com.blitzmax.app")
	settings.Insert("app.version.code", "1")
	settings.Insert("app.version.name", "1.0")
	settings.Insert("app.name", "BlitzMax Application")
	settings.Insert("app.orientation", "landscape")
	settings.Insert("app.comments", "landscape")
	settings.Insert("app.company", "My company")
	settings.Insert("app.description", "App description")
	settings.Insert("app.copyright", "Copyright")
	settings.Insert("app.trademarks", "All rights reserved")
```
What happens if you comment out one of the lines? Is Windows then using its own default value ("app.name" becomes "Application" or so) just because some other "app.***" things are defined. Or is Windows falling back to some other mechanism and using "binaryname" then as the name to display in the task manager.

If it was the first one - then we should provide "useful" default values. If it was the other option, then we should skip settings not "customized" by a "binary settings file".

**Comment by GWRon** [comment]
Correlated to #40

**Comment by woollybah** [comment]
Presumably, it just needs a settings file set up for it?

**Comment by GWRon** [comment]
yes I think it should get it's maxide.settings and it _should_ work. It also allows to add the https://blitzmax.org url somewhere.

**Comment by woollybah** [comment]
MaxIDE probably wants to be a bit of a showcase/example for all these things we've introduced...

**Comment by GWRon** [comment]
This is what I was talking about somewhere. All these little tools BlitzMax (NG) provides in a release should use the features NG provides (of course only if applicable).

**Comment by woollybah** [comment]
This should be working now - using the settings file and updated make.bmk.
