### ISSUE TITLE
Scaled Icons in the toolbar need overhaul

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#12]
The scaled variants of the toolbar icons miss some "black surroundings" around the "white surrounding" around the icons. Maybe it is because of `ResizePixmap()` using a simpler "resize algorithm".

On my Linux box it looks fine - but on Windows 10 ....
![toolbar](https://user-images.githubusercontent.com/2625226/47702936-cbbb9d00-dc1e-11e8-9f2f-60f4264efcfe.png)

zoomed:
![toolbar_3x](https://user-images.githubusercontent.com/2625226/47703031-2523cc00-dc1f-11e8-9cbf-495f6953637f.png)

... it looks a bit "damaged".

Also I wonder why the arrows have a blueish taint on my linux box but are black in my Windows box (did I miss an update?)

**Comment by woollybah** [comment]
I blame inkscape :-p
I can add the original SVGs to the project if that helps?

**Comment by GWRon** [comment]
Didn't your bah.mods contain something allowing handling of svg files (so makeicons can do it on its own)?

Else I could try to use the svg files if you provide them.

**Comment by GWRon** [comment]
Seems you once already had some "SVG viewer" thingy ready (QT):
http://mojolabs.nz/posts.php?topic=86562

I opened the SVG files in various programmes - and they seem to have certain "issues".

(older Adobe) Illustrator:
![illustrator](http://i.imgur.com/4oNdY1J.png)

Inkscape + Inkscape-export:
(see the greyish area on the right of the scissor in the SVG view already?)
![svgissues](https://user-images.githubusercontent.com/2625226/47852151-23066c80-dddb-11e8-97c4-4337be2e90d6.png)

Think the icons need to get saved by a tool displaying it properly. So at the end it might become compatible to (my) inkscape's capabilities of reading SVG files.

**Comment by woollybah** [comment]
Well, they come straight out of the Visual Studio icon library. I can't really vouch for Microsoft.. for anything really :-p

**Comment by GWRon** [comment]
Ok, your reply came meanwhile, so no edit of the old message ...

librsvg2-bin (`rsvg-convert in out` or `convert`) results in similar black rectangles than illustrator on certain SVGs.

I tried this to convert multiple variants:
```
#!/bin/bash
mkdir "$PWD"/png16
for file in $PWD/*.svg
    do
        filename=$(basename "$file")
        #--without-gui
        inkscape -z -e "png16/${filename%.svg}.png" -w 64 -h 64 "$file"
        convert -size 64x64 "$file" "png16/${filename%.svg}_convert.png"
    done
```
(convert somehow creates 16x16px files tough ...

**Comment by GWRon** [comment]
I converted them now "by hand" via this online tool here:
https://jakearchibald.github.io/svgomg/
(was pretty straight forward)

The "black rects" are gone, but Inkscape still has eg. issues with the scissor in the screens above. "[C]onvert" (or librsvg2-bin) was able to produce nice images afterwards - with exceptions 

![comparison](http://i.imgur.com/OxqMr8s.png)

I've gone back to the above said tool - and tried to uncheck some of the optimizations. I needed to uncheck "Remove unknown & defaults".

The resulting SVGs only differed in the first two lines:

broken
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
  <style>
    .icon-vs-out{fill:#F6F6F6}
  </style>
  <g id="outline">
    <path class="icon-vs-out" d="M10 7.414l2 2V4.586l-4-4-4 4v4.828l2-2V10h4z"/>
    <circle class="icon-vs-out" cx="8" cy="13" r="3"/>
  </g>
  <path d="M8 11a2 2 0 1 1-.001 4.001A2 2 0 0 1 8 11z" fill="#424242" id="iconBg"/>
  <path d="M11 5v2L9 5v4H7V5L5 7V5l3-3 3 3z" fill="#00539C" id="colorAction"/>
</svg>
```

working as expected
```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0" y="0" width="16" height="16" xml:space="preserve">
  <style type="text/css">
    .icon-vs-out{fill:#F6F6F6}
  </style>
  <g id="outline">
    <path class="icon-vs-out" d="M10 7.414l2 2V4.586l-4-4-4 4v4.828l2-2V10h4z"/>
    <circle class="icon-vs-out" cx="8" cy="13" r="3"/>
  </g>
  <path d="M8 11a2 2 0 1 1-.001 4.001A2 2 0 0 1 8 11z" fill="#424242" id="iconBg"/>
  <path d="M11 5v2L9 5v4H7V5L5 7V5l3-3 3 3z" fill="#00539C" id="colorAction"/>
</svg>
```

Why do I write this? We all want to learn something ;-)

**Comment by GWRon** [comment]
Sources miss "Go_16x.svg" - I think I just open up the "stop" and replace the color ...

**Comment by GWRon** [comment]
Ok, added new build and build-run icons (with a similar grayish-outline than the rest).

![comparison](http://i.imgur.com/JqFgiAd.png)

Ready to PR it for now - next step is to add the newly created 16x16px icons for win32 builds.

**Comment by woollybah** [comment]
Looks great. Thanks!

What's the 16x16 for?

**Comment by GWRon** [comment]
I was sure to have seen them scaled to 16*16 on win7 ... Will check that out later. Maybe it was 24*24 but then we need to "flatten" the symbols so they do not have multiple transparency colors.

**Comment by GWRon** [comment]
Seems the call to "SetMode EDIT_MODE" in maxide calls "RefreshToolbar()" - which is the source of these "borders". So what is done there? It enables or disables gadgets.

Once you disable icons in the "toolbar example" they look borked-up the same.

**Comment by woollybah** [comment]
So it's just Windows being... Windows. I'm happy to live with it :-)

**Comment by GWRon** [comment]
its not windows ... its MaxGUI I think - the way it draws "disabled" icons.

**Comment by woollybah** [comment]
So, it's Windows then :-p
MaxGUI just sends a message to indicate the current state of a particular toolbar button.

**Comment by GWRon** [comment]
But why does it work "nicely" in other applications?

Just open up "Paint" and the "insert" icon will be "grayscale + semi-transparent", copy something of the canvas and it gets colored nicely.
This is how I expect to look MaxIDE too.

**Comment by woollybah** [comment]
Maybe it's to do with that white border?
I dunno.

**Comment by GWRon** [comment]
What's that
```BlitzMax
	Method OnDrawItem(pDrawItemStruct:DRAWITEMSTRUCT)
```
in win32maxguiex.bmx for? I tried disabling it ... without visual differences (but it contains stuff for checking disable-state or pressed-state.

**Comment by GWRon** [comment]
If there was an option to render the toolbar elements on our own (similar to that `OnDrawItem`) thing then we could prepare icons accordingly (convert to grayscale and lower transparency). My Dig-Framework-code already contains some helpful functions for it).

**Comment by GWRon** [comment]
If we really want to stay with a "MaxIDE" then maybe it is better to realise the whole thing in with wxMax then. Filesize would increase but maybe some advanced features would become easier to achieve (layout, specific widgets, wizards).
