### ISSUE TITLE
Fix auto indent for scintilla textarea on win32

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#15]
Currently, the scintilla-based textarea on win32 does not touch on the event filter (which provides the auto indent functionality).

Either we could try to get the event filter working correctly on win32 or provide a "native" auto indent feature for the textarea. Scintilla provides enough capability to be able to implement this without too much difficulty.
On Linux(Gtk) keydown is already handled natively via a callback, and handed off to the event filter. Win32 uses WndProc to handle such events, but has been an issue getting the filter working via that.

**Comment by GWRon** [comment]
What should auto-indent do?
I assume it should do

```Blitzmax
Function Bla() 'press enter
    intendedCode...
End Function 'un-intended when pressing enter?
``` 
Same for switch, multiline-if, repeat, while ... and maybe even "rem"

so it intends when it found such a "opener", stores the depth it is currently in and when an "finisher" is found it decreases depth/indent-level ?
Think it should then of course have some kind of "stack" which explicitely says what is currently active ("if", "while", "function", "method", ...) so that a different finisher does not mistakingly lead to a depth-decrease (while the code is of course not working _in that moment_ but maybe it is a "typing while I am near this line"-change).

example:
```BlitzMax
Function Bla() 'enter
    If blubb 'do not finish the if here, first I add the "end function"
    End Function 'leads to decreased level
```
You could of course skip the "stack check" if the text area checks the whole text and so "auto corrects" the "End Function" when you added the "endif" on top.

**Comment by woollybah** [comment]
Well, I just want the basic functionality to match that of MaxIDE, which currently keeps the same indent as the last line when you hit Enter.

**Comment by GWRon** [comment]
Ahh, so it is just a thing of "extract whitespace before first char" thing (tab + spaces)?

- if first char is tab or space, check until you reach another char than tab/space and until then append these tabs/spaces to a StringBuffer"
- afterwards prepend this string buffer to the new line

This is it ... in essence?

**Comment by GWRon** [comment]
maxgui/maxguitextareascintilla.mod/win32.bmx contains this:
```BlitzMax
	Method WndProc:Byte Ptr(hwnd:Byte Ptr,msg:UInt,wp:WParam,lp:LParam)
			Local event:TEvent
		Select msg
			'Case WM_MOUSEWHEEL
			'	If (Long(wp)&MK_CONTROL) Then SendMessageW _hwnd, EM_SETZOOM, 0, 0
				
			Case WM_KILLFOCUS
				PostGuiEvent EVENT_GADGETLOSTFOCUS

			Case WM_CHAR
				If (keymods()&MODIFIER_CONTROL) Then
					Return 1
				End If

		End Select
		
		Return Super.WndProc(hwnd,msg,wp,lp)
		
	EndMethod
```
Shouldn't this be a place in which we could post another "gui event" - of course it does not handle "auto indent" then (needs "key down", not just "key_char").

**Comment by GWRon** [comment]
Ok, seems as if "super.wndProc" (aka "Tgadget.wndproc") already handles key down/char (just coded it again to see it afterwards ;-)) - it just is not received by the connected "filter".

**Comment by GWRon** [comment]
So I did it similar to other gadgets did ... and called a potential registered callback for keydown/keychar. 

maxgui.mod/win32maxguiex.mod/win32.bmx:
```BlitzMax
	Method WndProc:Byte Ptr(hwnd:Byte Ptr,msg:UInt,wp:WParam,lp:LParam)
		Local event:TEvent
		Select msg
			'Case WM_MOUSEWHEEL
			'	If (Long(wp)&MK_CONTROL) Then SendMessageW _hwnd, EM_SETZOOM, 0, 0
				
			Case WM_KILLFOCUS
				PostGuiEvent EVENT_GADGETLOSTFOCUS


			Case WM_KEYDOWN
				If (keymods()&MODIFIER_CONTROL) Then
					Return 1
				End If

				If eventfilter<>Null
					event=CreateEvent(EVENT_KEYDOWN,Self,Int(wp),keymods())
					If Not eventfilter(event,context) Return True
				EndIf


			Case WM_CHAR
				If eventfilter<>Null
					event=CreateEvent(EVENT_KEYCHAR,Self,Int(wp),keymods())
					If Not eventfilter(event,context) Return True
				EndIf
		End Select
		
		Return Super.WndProc(hwnd,msg,wp,lp)
		
	EndMethod
```
Using this leads to _maxide.bmx_'s function `Function FilterKey(event:TEvent,context:Object)` correctly listen to the key_down/key_char events.

If now setting the caret/cursor at the end of a line + pressing enter it will position the cursor correctly on the next line.
hitting enter another time leads to a "new line + newline". It somehow calculates stuff incorrectly.
Undoing stuff then lets a "[sub]"-glyph flash for a short amount of time. So for now it seems to bork up the "undo".

**Comment by woollybah** [comment]
The issue turns out to be that scintilla uses WM_CHAR events to drive content changes. Unfortunately, MaxIDE's filter stuff lets WM_CHAR fall through (whilst suppressing KEYDOWN), introducing an unexpected return character, which breaks autoindent.
