### ISSUE TITLE
Scintilla and breakpoints

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#17]
Once "scintilla" becomes the textarea of choice we could have the "breakpoint" indicator when there is a `debugstop` in the code. Also a `debugstop` could be added if you add a breakpoint in the "side panel" of the textarea.

Useful?

**Comment by woollybah** [comment]
I dunno. It seems like a major step change to start adding "marker" features.
Whereas everything I've done so far (apart from line numbers, which was the main reason for this) has been to support a "native" version of something that MaxIDE is already doing.

**Comment by GWRon** [comment]
Was just an idea. Minor thing.
