### ISSUE TITLE
Red text on Paste with scintilla textarea on Win32

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#18]
For some reason, pasting a chunk of code using the scintilla text area can result in the pasted text being coloured red (or perhaps the same colour as the bracket matching colour?)
It's almost as if the editor doesn't realise it needs to perform styling on the block.
If you edit the text at the start of the pasted block, it then styles everything as expected.

**Comment by woollybah** [comment]
This may not be valid any more...
It have never been a consistently repeatable issue. I'll just keep working with the new version using native bracket matching and see if it comes up again...

**Comment by GWRon** [comment]
I pasted some text (only 20 characters or so) today on a Windows MaxIDE - and it was bold and red for ... a second or so. It automatically refreshed style when I moved the cursor/caret by a position.

**Comment by woollybah** [comment]
But before the native bracket matching was implemented?

**Comment by GWRon** [comment]
Yes before. And it was on Windows - so might be even limited to that OS ?

Will keep an eye on it too - now with scintilla on Windows coding makes _way_ more fun with MaxIDE (proper UNDO/REDO and some known shortcuts...)

**Comment by woollybah** [comment]
I believe this is okay now.
