### ISSUE TITLE
Introduce native brace matching for scintilla textarea?

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#19]
Scintilla supports brace highlighting, it might be nice to also include this feature with the textarea gadget.

Matching starts by calling SCI_BRACEMATCH with the position of the first brace (either open or closed)
The result is the position of the matching brace or -1 if not found.
Calling SCI_BRACEHIGHLIGHT with the positions will style them the appropriate colour.
SCI_BRACEBADLIGHT can be used to style an "unmatched" brace a different colour.

We could then consider brace matching for supported non-bmx sources.

**Comment by GWRon** [comment]
Is this what the latest commit added?

**Comment by woollybah** [comment]
This is done :-)

**Comment by woollybah** [comment]
Indeed... :-p

**Comment by woollybah** [comment]
The native version is less likely to cause your code to think it has been modified...  which appears to happen in MaxIDE with its own matching code sometimes. - although I've yet to test this thoroughly.

**Comment by GWRon** [comment]
That's the benefit of relying on 3rd party code - and their experience (and bug fixing) ;-)

**Comment by GWRon** [comment]
Very minor: it does not work nicely with the "caret line feature": the background of the highlighted brace differs to the caret line background color.

Now one could fix that by defining a different background color for it - but what happens for a "multi line bracket match"? Seems scintilla itself does not offer a solution.
In our case _most often_ brackets/braces are on one single line, so it would work to style the color accordingly.

**Comment by GWRon** [comment]
One option (but then different to the "magui textarea"-implementation) would be to use an indicator:
https://www.scintilla.org/ScintillaDoc.html#SCI_BRACEHIGHLIGHTINDICATOR
and
https://www.scintilla.org/ScintillaDoc.html#Indicators

One could use "SCI_SETCARETLINEBACKALPHA" - using an alpha value results in the "colored rectangle" to get drawn _after_ the (styled) text. But this would only work for low-alpha colors - so some kind of "additive blend".

**Comment by woollybah** [comment]
Yes, I noticed this issue too.
The backalpha option works very well here when I have a dark background. If I set colour to white and alpha to 30, it looks really nice.
Not sure this would work on a white background though - you'd want the background to get darker...

**Comment by woollybah** [comment]
Actually, it looks okay, using a dark grey line style against the white background.
This may be the way to go - although some explanation may need to be given for the user to understand why they don't get the actual caret line colour - due to the alpha being 30 (out of 255)

**Comment by GWRon** [comment]
As we have a "preview" window below people could work it out on their own.
Aside of that we could just add a tooltip to the panel so people get their instructions.

Do not forget that "blending" means it adjusts the underlaying colors! so every color (except black) gets tinted by the color you use for the "alpha'd caret line".
It works well for gray (to brighten up or darken the background) but it won't work for colors (use a light blue - it will tint your orange, red, ... colors).

**Comment by woollybah** [comment]
I think it looks fine with alpha at 30.
I've also done the bracket styling too, while I was there...

**Comment by GWRon** [comment]
Don't worry - if there is someone blaming it we can still tinker around with it then. So the alpha-stuff will do - albeit I thought to have read it is not guaranteed to work on all implementations (cannot find it in the docs - so maybe I mix up stuff here). Still: as said we should keep it simple and use your new code. If someone has problems with it they can still raise an issue.

**Comment by woollybah** [comment]
This also works on other source file types.

**Comment by GWRon** [comment]
The alpha value is hardcoded. We should be able to customize it - even if MaxIDE used a hardcoded value of 30 then.

**Comment by GWRon** [comment]
Did you try it with a bright background too. Depending on how dark you choose your color the more visible the darkening of the underlaying text becomes.
Think it is less visible on dark backgrounds becore of the vibrance the text colors will most probably have. Stuff changes if you use a calm color palette.

While it fixes the issue with the brace matching I am not sure what to prefer ...
