### ISSUE TITLE
Syntax highlighting for "readonly" and "export" missing

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#2]
`readonly` and `export` should be of the same highlight type then `field` or `local`

**Comment by woollybah** [comment]
"Rebuild Documentation" should sort that out - assuming the keywords are documented -
* [ReadOnly](https://github.com/bmx-ng/brl.mod/blob/735558abb4802fe73ea53fecf1ff7b724ce72aa7/blitz.mod/blitz.bmx#L854)
* [Export](https://github.com/bmx-ng/brl.mod/blob/735558abb4802fe73ea53fecf1ff7b724ce72aa7/blitz.mod/blitz.bmx#L859)
