### ISSUE TITLE
Dependency on BRL.StringBuilder prevents building with legacy BlitzMax

### ISSUE THREAD

**Issue by HurryStarfish** [bmx-ng/maxide#21]
It seems MaxIDE fails to build with legacy installations of BlitzMax due to in import of `BRL.StringBuilder`. Compatibility could be restored by removing the import and adding the string builder code to the MaxGUI source instead, similarly to how it was done in bcc.

**Comment by HurryStarfish** [comment]
Ah yeah, I meant MaxIDE.

> I don't see much reason for keeping the NG-focused MaxIDE build compatible with the legacy compiler.

So the compatibility break in this case is intended then, I wasn't aware of that.
I've always been using the legacy compiler to build new versions of NG, to eliminate the possibility of any bugs in NG causing weird problems down the line. Maybe this isn't so relevant to MaxIDE. I think it would be good if bcc (and bmk?) stayed compatible with both compilers for the time being, though.

**Comment by GWRon** [comment]
I do the same.. compile the toolchain with vanilla to avoid potential bugs.
