### ISSUE TITLE
"Continue" icon not self-explanatory enough

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#24]
![img](http://i.imgur.com/lySn24v.png)

I just recognized during debugging that I was searching the "continue" button".

First of all I assumed it to be next to "stop" instead of being left of the "step in/out" buttons. Then I was looking for some kind of "arrow" as in classic "play" symbols.

So ... replace symbol with a triangle (facing right) and maybe place it next to the stop?

**Comment by GWRon** [comment]
I would even suggest to move the "stop" left of the stepping-symbols. So its "Build | Continue | Stop ... | Step | Step In | Step Out".

**Comment by woollybah** [comment]
Yes, maybe we should have a play/arrow icon there instead.

**Comment by GWRon** [comment]
Will PR soon - meanwhile found that when compiling "quick" the incbin changes are not fetched. Disabling "quick" and I got:
```
[ 15%] Compiling:maxide.bmx.release.linux.x64.incbin.c
```
