### ISSUE TITLE
[Win32] Dropped file recreated as ".filename.bmx"

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#25]
When I tried to compile bcc.bmx I dropped it on the "help" window of a fresh started MaxIDE.

In discrepance to dropping it on the "nav button bar"/tabbar this created a new file : "[dot]bcc.bmx". Think it happens as the "help window" reacts like a small browser window - and just did some kind of local file download.

This also created a "[dot].bcc.bmx" file in the very same folder as "bcc.bmx" was located in.

**Comment by woollybah** [comment]
I believe this is a feature, not a bug, and is what happens when you click on one of the doc examples while in the help.
So the action is probably to create a new file with a dot prefix when the html view wants to open something with a .bmx suffix ?

**Comment by GWRon** [comment]
Seems "GTK Scintilla" intercepts dropping files onto the "textareas area". Need to handle "SCN_URIDROPPED" there.
On Windows the DragNdrop works differently.
