### ISSUE TITLE
Improve handling of IDE restarts

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#30]
It would be nice if the IDE could remember **where** in the editor you were working last when the IDE starts up the next time.
We'd probably need to save the cursor position, and the last open tab, at the very least.

Also, it would be nice, on Win32 (at least), to be able to have the IDE restart automatically after a system reboot. (see https://github.com/bmx-ng/maxgui.mod/issues/24)

With both of these additions, life might be a little better ;-)

**Comment by GWRon** [comment]
Maybe it should not store only the cursor position of the active tab... But for all.

So it yoz restart it should forget about debugger values but else it should be the same as if you did not restart.


In short:
- next to open tabs we should store individual cursor positions
- store active tab

**Comment by woollybah** [comment]
Yes, that's what I said :-)

**Comment by GWRon** [comment]
Would try to do that this afternoon - wife decided to give me some sparetime without kids ;-)

**Comment by GWRon** [comment]
I first thought about appending the information to the file uri in the "file_open" line of the config:
````
file_open=c:\bla.bmx::2::4
```
or so.
But then I thought to better write it that way:
```
file_open=c:\bla.bmx
file_meta=1::4::whatever_we_store_else::and_even_more
```
Meta would be a special "TSourceDocumentMetaData" object which can get extended ... to contain more data if needed. Eg. Breakpoints, selection masks, ...

On the other hand it means to add maybe unneeded complexity...


At the end we could mix both: have all in one line - but deserialize the part after "uri" into a special container/type.

**Comment by GWRon** [comment]
Ok, so final lines look like this:
````
file_open=c:\bla.bmx|0|100
file_open=c:\otherbla.bmx|1|12345
```
First appendix is 0/1 indicator of whether it is an active panel (wanted to avoid adding a "file_active=c:\otherbla.bmx"

During loading it marks an "active" as the one to choose after finished creating all code panels. Once this is done - it activates that panel (to avoid activating with other panels getting created afterwards).

During loading of the panels the "cursorPos" is set and the `SelectTextAreaText` is called accordingly.


I am not at home now so I will Pull Request later on (except there is an interception by you - eg if you want to store "text selections" too)

**Comment by woollybah** [comment]
I don't care about text selections. It doesn't seem useful.

**Comment by GWRon** [comment]
It would help if you use it...and you get that restart.


But yes..would only be a goodie.

**Comment by GWRon** [comment]
If the pull request fullfills your wishes it is up to you to close this issue then.

**Comment by woollybah** [comment]
Seems to be working well mostly, except for some quirks on Linux.
