### ISSUE TITLE
Handle Win32 shutdown/log off events

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#32]
It's possible to understand that Windows is shutting down and do something about it - perhaps stopping it if there are unsaved files, or just ensuring that the IDE is closed properly rather than terminated.

It would be nice if the IDE behaved better and didn't just terminate.

Some stuff about it here : https://www.apriorit.com/dev-blog/413-win-api-shutdown-events

**Comment by GWRon** [comment]
Think this is an advanced subject... Only helping in rare situations (at least imho).

Remember that we only dirty little patches to the maxide codebase (which would need a big overhaul if it is planned to get improved so much).

Maybe efforts are better done in an existing-IDE language-plugin

**Comment by woollybah** [comment]
Well, currently, when Windows restarts because of an update, my open MaxIDEs appear to be simply terminated. They do not "close" and save their current configuration.
Which is somewhat annoying when you come to do some work the next day only to find you need to set everything back up again.

If there was a way I could prevent Windows not updating while my laptop is hibernating, I'd do that, but nothing I've tried has worked, so the next logic step is to make MaxIDE behave properly by closing itself when required, and restart after the reboot, leaving itself in pretty much the same state as it had been in when I'd closed the lid of my laptop the previous day...

**Comment by GWRon** [comment]
Next to the MS specific thing we could simply add a timer... And save the config every 5 seconds ... Of course this would not be nice for idling / sleep states.

**Comment by woollybah** [comment]
Nah.

Depending on what Linux raises, we can maybe handle that too. I expect we could handle a SIGTERM and close nicely if required.

Perhaps these things should raise an App Terminate event or something in MaxGUI...

**Comment by woollybah** [comment]
Well, that's pretty cool :-)
MaxIDE is now saving its state, and opening again after a restart.

I think I'll add it as an "IDE Option" that you can turn on or off - probably default on.
Once your changes for remembering cursor location is added, I'll be a much happier BlitzMax Windows user... and Windows Updates won't bother me so much.

**Comment by GWRon** [comment]
Will add this later evening. Wife left the younger one with me...and he is currently...a bit difficult to handle. Goodbye afternoon sparetime :-)

**Comment by woollybah** [comment]
This seems to be working well now :-)
