### ISSUE TITLE
Linux initial tab is always the Help page

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#35]
Now we have MaxIDE remembering the last tab and cursor position that was being used when it is shutdown, it would be nice if it could return to the same place when it is restarted.

This seems to work as expected on Windows.
On Linux, it always starts with the Help page.

I had a quick look into it, but I couldn't get it to work differently. It may be a timing issue with Gtk or something. Perhaps it needs to be done as after a delay, or once everything has finished loading...

**Comment by GWRon** [comment]
Then this is differing between our both systems (aka it works here) -> which implies it is a timing issue.

**Comment by GWRon** [comment]
Seems "SelectPanel()" is called after the restore took place. As said I will check it during lunch break.

**Comment by GWRon** [comment]
Ok, had a look at it ...

gtk3maxgui.mod/gtkgadget.bmx - TGTKTabber - OnTabChanged() is called a lot of times when it isn't needed.
```
Executing:maxide.debug
ontabchanged
DebugLog:WARNING: Toolbars should *only* be parented to window gadgets.
ontabchanged
ontabchanged
ontabchanged
ontabchanged
ontabchanged
AddPanel(): SelectPanel tabpanel
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
ontabchanged
AddPanel(): SelectPanel tabpanel
SelectPanel(): /home/ronny/Arbeit/Programmieren/Projekte/BlitzMaxNG.project/maxide/maxide.bmx
ontabchanged
AddPanel(): SelectPanel tabpanel
SelectPanel(): /home/ronny/Arbeit/Programmieren/Projekte/GenusPrime/GenusPrime.bmx
ontabchanged
AddPanel(): SelectPanel tabpanel
SelectPanel(): /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/tmp/untitled1.bmx
SelectPanel(): 
ontabchanged
```

Each time it does "ontabchanged" it sends out an event "EVENT_GADGETACTION" which maxide.bmx catches for "tabbar" and then activates this tab.

The TGTKTabber contains a property "ignoreChange" which we might utilize for our needs - to disable any activations until everything is initialized - and to manually call a tab activation afterwards.
This would require some `?Linux` conditionals and `TGTKTabber(tabbar)` casts which I think is a dirty way of fixing it.

So ... do it that way or try to fix it "properly" ?

**Comment by GWRon** [comment]
Strike above  - I forgot about the second tabber (debug/code-panel thing). So GTK wise it seems to do what it should (or not?) - just need to find out why "SelectPanel()" is called. It is an reaction to the said "EVENT_GADGETACTION" which is ... only sent once 

This is odd as `OnTabChanged()` is executed each time we add (and therefore "select") a panel/document.

So I checked when stuff is emitted and when ...received.
```
Executing:maxide.debug
ontabchanged 0 current: -1  widget: 38581312
  -> send out PostGuiEvent(EVENT_GADGETACTION, TGadget(obj), index,,,,TGadget(obj).ItemExtra(index))

AddPanel(): SelectPanel tabpanel
ontabchanged 1 current: 0  widget: 38581312

AddPanel(): SelectPanel tabpanel
SelectPanel(): /home/ronny/Arbeit/Programmieren/Projekte/BlitzMaxNG.project/maxide/maxide.bmx
ontabchanged 2 current: 1  widget: 38581312

AddPanel(): SelectPanel tabpanel
SelectPanel(): /home/ronny/Arbeit/Programmieren/Projekte/GenusPrime/GenusPrime.bmx
ontabchanged 3 current: 2  widget: 38581312

AddPanel(): SelectPanel tabpanel
SelectPanel(): /home/ronny/Arbeit/Programmieren/Tools/BlitzMaxNG/tmp/untitled1.bmx

EVENT_GADGETACTION for tabbar
SelectPanel(): 
ontabchanged 0 current: 3  widget: 38581312
```
As you see the emitted event from "start" is received at the end.

**Comment by GWRon** [comment]
A dirty fix would be:
```BlitzMax
Type TCodePlay
	?Linux
	Field handleActivatedTabOnStartup:int = False
	?
'[...]
	Method Initialize()
'[...]
			If activePanel
				SelectPanel( activePanel )
				?linux
				handleActivatedTabOnStartup = true
				?
			EndIf
'[...]
	End Method

	Method poll()
'[...]
					Case tabbar
						?linux
						'skip first incoming tabber event as it is received
						'delayed from the GTK widget
						if handleActivatedTabOnStartup
							handleActivatedTabOnStartup = false
							return
						endif
						?
						Local index = EventData()
						If index>=0 And index<panels.length
							SelectPanel panels[index]
						EndIf
'[...]
		EndSelect
	EndMethod

EndType
```

While it works it feels dirty and just "patches" a bug.

**Comment by woollybah** [comment]
What if we had a few extra PollEvents (or whatever) during the startup process?
Presumably, we only see the event because we've been really busy up til that point?

**Comment by GWRon** [comment]
I did a pollsystem thing in too..but this means you will also eat other events...

**Comment by woollybah** [comment]
Okay, so the Windows code tries hard not to generate events when something has occurred programmatically, which seems reasonable.
The Gtk code should probably attempt to do this too.

**Comment by woollybah** [comment]
I think my commit has sorted it. Thanks for your assistance :-)
