### ISSUE TITLE
MaxIDE crashes on invalid native '! command

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#36]
Put this in a new document in MaxIDE:
```BlitzMax
SuperStrict
Framework Brl.StandardIO

global a:string 

'!printf("hi %s", a);
```
Executing will exit MaxIDE.

Alter the native commant to be `'!printf("hi %d", a)` (%d) and execute it - you get the error about "a" being a "first use" (not declared before).

**Comment by woollybah** [comment]
I get a compilation error.
Since the build failed, there is nothing to execute.
