### ISSUE TITLE
[Minor] Hide invalid options for vanilla/NG

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#37]
Currently MaxIDE shows `Threaded` for NG and for Vanilla all the developer options of NG.
Similar to `GetBMK` it could have a `GetBCC` and hide options accordingly.

If this is not of interest then "threaded" could get auto-checked (and disabled - and maybe even relabelled as "threaded by default") for NG builds so people know it is threaded by default.
Together with this BMK should no longer append ".mt" to NG builds as they always are threaded and should not need any extension.

**Comment by woollybah** [comment]
I don't know which version of MaxIDE you are using, but I don't have a Threaded option here, nor does it append `.mt` to my builds.

For Vanilla, you may want to use the original MaxIDE instead. NG's MaxIDE is developed with NG in mind.

**Comment by GWRon** [comment]
Hmm I even commented on the commit ... ;-)
