### ISSUE TITLE
Menu shortcuts and textarea keycodes

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#46]
Coming from the discussion in this commit: https://github.com/bmx-ng/maxide/commit/f61d249be19be51cdbb2d930669ceefc37582188

MaxIDE uses "FilterKey()" to handle certain shortcuts - here "TAB" and "Shift + TAB".
When using that same shortcuts in menu points you will run into trouble (eg two times executed indentation/outdentation).

So I simply checked when "FilterKey()" is called and when the menu-action (via shortcut) gets triggered).

On my Linux box (so "GTK") I hit TAB and see:
```
FilterKey()
```

On My 64Bit XP Box I hit TAB and see:
```
FilterKey()
MENUINDENT: invoke toolindent
```

So on my Windows box both gadgets (textarea and menu entry) get the information about the key hit there - while on Linux only the textarea receives it.

The "FilterKey()" was cleaned from the portion doing the block-indent - so it does not get filtered out on the Windows ("non gtk"-textarea and also with "scintilla"-textarea) box.

**Comment by GWRon** [comment]
Hmm ... so one of the options was
> - remove shortcut "interaction" from menu but still display the text there (dunno how to do that - in windows "label {{shortcut text}}" would work - but this is no GTK solution)

To achieve this we need to change "win32maxguiex.bmx":
```BlitzMax
Type TWindowsMenu Extends TGadget	
[...]
'add this:
	'override
	Method SetSensitivity(flags)
		'remove hotkey (interaction) if sensitivity is to ignore keys 
		If flags & SENSITIZE_KEYS = 0 And _hotKey
			RemoveHotKey(_hotKey)
		EndIf
		Super.SetSensitivity(flags)
	EndMethod
```
Now we could call `gadget.SetSensitivity(SENSITIZE_MOUSE)` and it would remove the hotkey we just defined. 
So in maxide.bmx we would need to do this:
```
Local g:TGadget
		g = CreateMenu("{{menu_edit_blockindent}}",MENUINDENT,edit,KEY_TAB)
		SetGadgetSensitivity(g, SENSITIZE_MOUSE)
		g = CreateMenu("{{menu_edit_blockoutdent}}",MENUOUTDENT,edit,KEY_TAB,MODIFIER_SHIFT)
		SetGadgetSensitivity(g, SENSITIZE_MOUSE)
```
The entries get created with the key codes as accelerator but the sensitivity change then removes the interaction part for these key codes.


With a `?win32` conditional we could even skip all this stuff and do a direct call:
```BlitzMax
		g = CreateMenu("{{menu_edit_blockindent}}",MENUINDENT,edit,KEY_TAB)
		?win32
		TWindowsMenu(g).RemoveHotKey()
		?
```
This would be needed as this method only exists for the win32-implementation of MaxGUI gadgets.


Still this feels like a dirty "workaround" instead of a proper solution. 

@woollybah 
Would you accept such a "hack" to workaround for shortcuts defined in the menu and also used in the textarea?

**Comment by GWRon** [comment]
test ... I just wrote a longer reply but it is not displayed here?

**Comment by woollybah** [comment]
The post order seems a bit mixed up here... as you also have noticed :-p

No awful hacks please. I don't really think it's worth spending any time on this at all really, as there are much more useful things to be getting on with than these extreme edge cases.

I see two options here :
* leave things as they are - with the menu shortcuts as they are, and otherwise things working as they have been up til now.
* remove the block indent menu items that are bothering you so much.

Otherwise, I see little point creating work just because.

**Comment by GWRon** [comment]
> No awful hacks please. I don't really think it's worth spending any time on this at all really, as there are much more useful things to be getting on with than these extreme edge cases.

Dunno if my PR is an awful hack but at least it seems to fix the issue here.
As said the underlaying MaxGUI is doing something "different" here I assume, so it needs some quirks to  get stuff working.

Glad that copy/paste are done differently - as it would else be affected too (duplicate copy, duplicated paste when using scintilla).
