### ISSUE TITLE
Add support for new -upx build option

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#49]
`bmk` now supports using [UPX](https://upx.github.io/) as a post `makeapp` step.
We should probably add a new toggle menu item for this. It would also be nice if it could detect the presence of the upx executable and therefore enable/disable the menu item appropriately.

**Comment by GWRon** [comment]
Would do that - just need to know where the option is to put to  - I think "build options" might be suitable (sets BMK options) but it is more about the "build process".

"app options" would suit too somehow - but ... it seems to be "app type"-specific for now.

I think it needs a bit more than just the UPX check.

- check existence of UPX[.exe]
- disable menu entry when "shared lib" is set as app type

**Comment by woollybah** [comment]
Maybe we'll need another sub-menu... `Misc Options` or something, for those that don't fall into any of the others...

**Comment by GWRon** [comment]
If done then properly ;-)
![](http://i.imgur.com/NZqp2ox.png)

Not correct - as an "NG MaxIDE" could get rid of the FASM stuff (and other "legacy" code lines).

**Comment by GWRon** [comment]
While I see it on the screenshot above - maybe the copyright-text should be updated to represent the current state.

**Comment by woollybah** [comment]
Yes. That's what I thought you were talking about when you mentioned "other legacy code lines".

**Comment by GWRon** [comment]
Yes - some minutes earlier I did not want to call the child by it's name ;-)

But else I am explicitely talking about:
SVN stuff in MaxIDE
SyncMods functionality ...
...
or replace them with NG-specific stuff - which would add another thing to "take care about" (which we initially did not want when it came to MaxIDE being only a "necessary evil").

**Comment by woollybah** [comment]
Oh, I see... I thought you were referring to the dialog.
Yes. I was going to mention the SVN stuff, at least.

I've no plans to replace them with anything.

**Comment by woollybah** [comment]
Do we support wrapping labels in MaxGUI? (see your long path in the dialog as an example)

**Comment by GWRon** [comment]
Saw that too ...but I think not all UIs have multi-line labels.

**Comment by GWRon** [comment]
> Oh, I see... I thought you were referring to the dialog.
> Yes. I was going to mention the SVN stuff, at least.
> 
> I've no plans to replace them with anything.

If we removed SVN we could remove the whole "project manager" (which has nothing to do with "locked build files" or so).

**Comment by GWRon** [comment]
I removed project support and SVN stuff (only used in projects). If not of need, just reject the corresponding PR.

**Comment by woollybah** [comment]
Hold on...  I use the "projects" stuff... to manage applications within MaxIDE.

**Comment by woollybah** [comment]
SVN <> Projects :-p

**Comment by GWRon** [comment]
OK ... so what are you using of "projects" ?
I only saw the popup menu in the right pane ... and that you can setup directories.
What benefits do they have?

**Comment by GWRon** [comment]
I removed the SVN stuff - but needed to adjust the button positions too (redid calculations). Think "find in files" would need this adjustment too but I will skip that for later (until I see it's OK what I did).

**Comment by GWRon** [comment]
The problem with gui stuff is... if I layout it properly on my Linux box, it is not guaranteed to look ok on Windows...

**Comment by woollybah** [comment]
Sure it is. You just need to take into account the platform with the larger size of controls, and space things out based on that...
We know that MaxGUI is rubbish when it comes to actually doing layouts and such, but you just need to work within the limits that are presented to you. ;-)

I didn't think there'd be much to change?

**Comment by GWRon** [comment]
There wasn't much to do - until I saw these odd button displacements :-)
