### ISSUE TITLE
Toolbar icon improvements

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#5]
Since we now have a new main logo, it would be nice to have an updated set of toolbar icons too.
There's probably a free icon set somewhere that might cover most of the icons we currently have.

I'd suggest we have a base set of SVG icons that we can then scale for different configurations.

**Comment by GWRon** [comment]
Best thing would be to use the OS defined icons.. to make it look more native.

Rocket icons would be blue...as they are custom and important.

**Comment by woollybah** [comment]
The flat-styled icons from the Visual Studio Image Library (2017) are okay, namely these :
```
NewFile
OpenFile
CloseDocument
Save

Cut
Copy
Paste
Search

..
..
StepOver
StepIn
StepOut
Stop

Home
StepBackwards
StepForwards
```

They are free to use, and we can include a copyright in the credits page for them.
They fit in with the general styling of the new flat-look rocket logo.

**Comment by GWRon** [comment]
Is there a simple package file containing all the icons?

I thought of something like referencing a "native icon" ... that way it would use the "file open" icon the OS-theme defines, not the app. There is a reason that most of my GTK-Apps look "similar".

**Comment by woollybah** [comment]
I've converted the above icons into sets of 24, 48 and 64 px pngs, and currently modified the included makeicons app to generate strips of those sizes.
They look okay on Windows.
