### ISSUE TITLE
Add Locked buildfile indicator to toolbar

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#51]
When an application is running the toolbar changes some symbols to indicate "there is something running".

While I extended my Geany plugin to have a "lock/unlock"-icon (indicating whether there is something locked or not + unlocking or locking the current when clicking on it) I thought it would be a good idea to have such a "prominent" indicator in MaxIDE too.

We could use different icons:
- open lock (nothing locked yet)
- closed lock (a build file is locked)
- tinted closed lock (currently activated document is the locked one)
- disabled symbol for "non .bmx"-files (so you still see "locked or not" but cannot "lock" that)

clicking on "open lock" locks the current file as build file (if clickable).
clicking on "closed lock" removes lock of the current build file

What do you think? Should I prepare some icons?

**Comment by woollybah** [comment]
Yes, that seems reasonable.
I'd also consider adding another menu option related to that, something like "Open locked file", which would take you to the locked file - helpful if you have lots of tabs, for example. It would be disabled if there isn't a lock.

**Comment by GWRon** [comment]
Yes that sounds useful.

**Comment by GWRon** [comment]
![](http://i.imgur.com/HHuS5Z9.png)

unlocked / locked / goto locked

**Comment by GWRon** [comment]
Would be easy to add - I thought.
The problem is that maxide defines constants - and then tries to access stuff within the toolbar based on these constants.

With "continue" being removed from the toolbar (its just there to replace another icon during debug-stop) one would have to subtract "1" from the constants ...

I see two solutions:
- hide the icon instead of removing it (is that even possible?)
- create a "mapping" (toolbarConstants->toolbarIndices)

Dunno if one could hide a single icon of the toolbar (not remove it) so it sounds as if it needs the mapping then.

**Comment by GWRon** [comment]
Got it working ... partially (goto is still missing).

@woollybah 
Do you have an idea why the toolbar isn't showing the separators on Linux?
The "gtk_separator_tool_item_new" is called accordingly but they are not visible ?!

Top: Geany (GTK)
Bottom: MaxIDE (GTK))
![](http://i.imgur.com/8cWkxfM.png])

**Comment by woollybah** [comment]
No idea why it isn't rendering the lines. The code looks correct.

**Comment by GWRon** [comment]
Does it render on yours ?

**Comment by GWRon** [comment]
I even added `gtk_separator_tool_item_set_draw` to gtkcommon.bmx and enforced the separators to be drawn.

gtkgadget.bmx
```BlitzMax
			
			' no image? Then this is a separator!
			toolitems[index] = gtk_separator_tool_item_new()
			' set the separator visible
			gtk_separator_tool_item_set_draw (toolitems[index], true)
```
But it did not help.

**Comment by GWRon** [comment]
As written in the other issue: it is a matter of the theme (Mint-X GTK3 seems not to show separators). GTK2 Applications use the GTK2-variant of the theme which has visual separator lines - my old MaxIDE used GTK2 and therefor had lines, Geany is GTK2 and has lines, most other applications here with toolbars were GTK2 (or did not dynamically link to it so I dunno).


Back to "lock/unlock" ;-)
