### ISSUE TITLE
Projects: 'Explore' has no use

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#56]
The popup menu of projects contains 'Explore' which executes `OpenUrl()`. The path it uses is the local project folder URI.
So instead of viewing it in a browser (or at least trying to do so) it should open up the file manager of choice:

Windows: explorer.exe
Linux: xdg-open URI
Mac: ?

**Comment by woollybah** [comment]
Explore works for me here on Windows. It opens the chosen folder explorer.

**Comment by GWRon** [comment]
I tried it on windows 7 and it started the internet explorer

**Comment by GWRon** [comment]
Added a fix for Linux' `OpenUrl`
