### ISSUE TITLE
Improve HiDPI support

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#6]
If I build MaxIDE (on Windows) with HiDPI enabled, the toolbar icons and tabs are frighteningly small and hard to read on my 15" laptop screen.

We should add options to change both the toolbar icons size and the font size for tabs - the navigator tree font and editor text is already configurable.

**Comment by GWRon** [comment]
Can't we have a "2x" option? Scaling fonts and using an other icon set?

**Comment by woollybah** [comment]
I should also add, that all dialogs, including the splash, are also very small indeed.
