### ISSUE TITLE
New icon has black background

### ISSUE THREAD

**Issue by woollybah** [bmx-ng/maxide#8]
The new rocket icon appears to have a black background.

![icon_black_bg](https://user-images.githubusercontent.com/95883/47511050-47a99400-d871-11e8-9d48-bd022a018dfa.png)

It would probably be better if the background was transparent.

**Comment by GWRon** [comment]
It is not black...but a real "background".

I could have a white outline (for darkish themed windows...)... But for 16*16 you need to sacrifice stuff then (especially without alpha channel transparency but a single color transparency).

Am 25. Oktober 2018 17:17:38 MESZ schrieb Brucey <notifications@github.com>:

**Comment by GWRon** [comment]
This is the current "maxide_icon.png":
![maxide_icon](https://user-images.githubusercontent.com/2625226/47525503-b7357880-d89d-11e8-826e-d4a19e007916.png)


And this is the icon which is placed in the "application caption/header" of __Win32-applications__ by maxide.bmx itself:
![window_icon](https://user-images.githubusercontent.com/2625226/47525556-d2a08380-d89d-11e8-8102-76ca99f2d633.png)


This variant here has a white outline (ready to replace the "maxide_icon.png" if you really wanted it):
![maxide_icon_white_outline](https://user-images.githubusercontent.com/2625226/47525738-46db2700-d89e-11e8-9f67-5b60c8f8d709.png)


Preview:
![maxide_icon_white_outline_preview](https://user-images.githubusercontent.com/2625226/47525896-9f122900-d89e-11e8-913d-eb5a6991f75b.png)

**Comment by GWRon** [comment]
Is some new media stuff needed or is the issue no longer valid?

**Comment by woollybah** [comment]
I don't remember. I'll need to look into it.

**Comment by GWRon** [comment]
think this can be closed?

**Comment by woollybah** [comment]
Is it not an issue for you now?

**Comment by GWRon** [comment]
You can get used to so many things. And I cannot close as you are the issue creator :-)
