### ISSUE TITLE
MaxIDE doesn't launch on Windows 7

### ISSUE THREAD

**Issue by DruggedBunny** [bmx-ng/maxide#84]
Hi Team,

I know people's opinions on the use of Windows 7 (spare me!), but I'm wondering if it's expected that the latest blitzmax.org x86/x64 release fails on 7? I think bmx-ng has been quite older-OS friendly!

I hadn't updated my copy for a long time but on installing I now get this on launching MaxIDE:

```
---------------------------
MaxIDE.exe - Entry Point Not Found
---------------------------
The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```

... so assume CreateFile2 is a later OS function. Is it actually necessary for anything?

![noto7](https://github.com/bmx-ng/maxide/assets/1781537/383ccc04-8a3c-4178-99ba-c8d720ff1fd9)

**Comment by DruggedBunny** [comment]
Replaced with my older release but then got same from bcc... all built to later platform target?

**Comment by DruggedBunny** [comment]
I'll close this (not going to be a popular option anyway, ha ha) and will try rebuilding the pieces later.

**Comment by GWRon** [comment]
reference https://github.com/bmx-ng/pub.mod/issues/68

So to fix it, physfs lib needs to be updated (not by you).

So - please reopen the issue until resolved. As this means that each weekly build for now (until fix) does not have a working MaxIDE on older Windows.

Edit: the first post in the referenced issue contains a link to some other issue I raised - maybe for now you could adopt the source code to use "non createfile2" in your case.

**Comment by DruggedBunny** [comment]
Oops, sorry GWRon, assumed it was really going to be my problem! Wasn't really expecting 7 support in fairness, unless it was a cheap/easy fix... reopened!

I'll have a look at your post later on and see if I can get it working -- thank you.

**Comment by GWRon** [comment]
Did not test it - but the only change you should need to do is:
https://github.com/icculus/physfs/commit/cc2da5ab96cc79c5132017ad8f5bf60ab7243414

But this requires a more recent Windows to use the current build to recompile the binaries (bcc, bmk ..., maxide) or older releases capable of building newer sources (you know ... hen, egg :D)

Could build them for you I guess.

**Comment by DruggedBunny** [comment]
Daw, thank you! I'll give that a go tonight, I have 11 so will contain my rage tonight and give it a whirl!

(Meant to be working right now...)

Appreciate it, will report back

**Comment by GWRon** [comment]
I used a December 2023 based build of NG to compile "todays" bcc, bmk and maxide source based binaries.

Am not sure if you use 64bit, so I did 32bit builds:
[bmx.tools.zip](https://github.com/bmx-ng/maxide/files/14884798/bmx.tools.zip)

I only changed what the physfs-lib changed (link given in the reply above). So with the replaced binaries you should be able to build other tools on your own (if you need them).

Anyways - hezkore/vemod made a Visual Studio Code extension for BlitzMax, so you might prefer to give that a whirl instead of maxIDE (it still works but lacks some convenience thingies :D).

**Comment by DruggedBunny** [comment]
Nearly there! It gets to 'rebuild docs?' but then makedocs fails with same result. Just tried running docmods on a double-click and that does same, but hopefully that would be it!

Not really expecting you to build 'em for me! But can you peel me a grape while you're there? |D

**Comment by DruggedBunny** [comment]
Not sure if I have the Max extension for Code... I might have it but prefer the basic form!

**Comment by GWRon** [comment]
yeah ... as said you need to build the other tools on your own (makedocs, docmods) (simply decline building docs in MaxIDE on first run)
So you should look in the "sources" folder - there these tool sources should reside.

I can do of course too but thought you'd feel a bit safer if at least some binaries are not "3rd party build" :)

**Comment by GWRon** [comment]
makedocs and docmods builds:
[src.zip](https://github.com/bmx-ng/maxide/files/14884943/src.zip)

**Comment by DruggedBunny** [comment]
Argh, so close! (I'm happy to run your builds of course.)

It all works now... except compiled exes give the same error! So obviously it's linked into the output code somewhere, might be a bigger challenge?

(MaxIDE just highlighted a stupid error in my code, too, trying to return a float value in a function with undefined return type, so that was nice!)

**Comment by GWRon** [comment]
Did you change the code in pub.mod/physfs.mod (as I wrote multiple times) before doing all these compilation tries? 
Once you compiled brl.mod (here io.mod) without that change you will have to recompile them again once you changed that single line in that physfs-source file.

open `mod/pub.mod/physfs.mod/physfs/src/physfs_platform_windows.c`
search :
```
#if defined(PHYSFS_PLATFORM_WINRT) || (_WIN32_WINNT >= 0x0602) // Windows 8+
```
replace with :
```
#if defined(PHYSFS_PLATFORM_WINRT) // also available if targeting Windows 8+ || (_WIN32_WINNT >= 0x0602) - but do not include this for now, due to common toolchain defaults
```

finally run 
`BlitzMax/bin/bmk.exe makemods -a brl`

**Comment by DruggedBunny** [comment]
No, sorry, I just dropped your builds in thinking it would just be affecting those on a quick scan, but I'll mod the other bits tonight and report back!

**Comment by DruggedBunny** [comment]
Hi @GWRon (and @woollybah), started over again today, rebooted to 11, installed the latest blitzmax.org release and replaced pub.mod as I saw Brucey's update. Basically rebuilt all modules and executables and, woo! All working in 7 now!

Thanks for looking into this and the amazingly quick fix, really appreciate it. Next full release should be good on 7.

I'll close the issue but shout if you need it reopened. Thanks again!
