### ISSUE TITLE
New "Build Option" "generate .def file (only shared libs)" needed.

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/maxide#9]
New "Build Option" "generate .def file (only shared libs)" needed.

When building a .dll it might be useful to have the corresponding "generate .def file" bmk-parameter exposed to MaxIDE somehow.

**Comment by woollybah** [comment]
The bcc "-def" argument?
It's (currently) automatically applied when makelib is enabled.

**Comment by GWRon** [comment]
Ahhh you're right... I somehow used a BMK of earlier september on that computer (local installation as it is faster than running from a portable USB stick).
Updated BMK ... and this issue got obsolete :-)

Nonetheless - maybe the opposite might be required ("do not generate .def file") ?


While generating a DLL I got:

```
Warning: resolving _MyFunc by linking to _MyFunc@0
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
Warning: resolving ....

Process complete
```

Dunno if I expose it correctly and we should use above's "--enable-stdcall-fixup" or if I have to do something in my code (using `Function MyFunc:Int() Export "Win32"` for now).
Also curious as there is "_" prepended to the functions (while the .def file contains no prepended underscore).

**Comment by woollybah** [comment]
The warning is probably because it is generating the def file with two sets of exports, one with stdcall suffix and one without. It may be that we should just export one set with whatever suffix it requires for a particular function. Then it wouldn't need a "fixup" to remove the warnings.
